Docs: add a sample workflow for Application Integration connector
GoogleCloudPlatform/workflows-samples pull request #167
Opened 2022-11-11 18:48 UTC by j9che

2022-11-14 20:46 UTC, iennae commented
@j9che can you provide the team name for who will be responsible for updating/maintaining this sample? Thanks.

2022-11-14 20:56 UTC, j9che commented
> @j9che can you provide the team name for who will be responsible for updating/maintaining this sample? Thanks.

@iennae I've added my team name in the description.

2022-11-14 21:12 UTC, averikitsch requested changes

2022-11-16 16:59 UTC, averikitsch approved these changes

2022-11-16 16:59 UTC, merged